-- MySQL Script generated by MySQL Workbench
-- Thu Feb 24 11:59:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(16) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_image` VARCHAR(350) NULL,
  `roles_ID` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_ID`),
  INDEX `fk_users_roles1_idx` (`roles_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_ID`)
    REFERENCES `mydb`.`roles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `IDgenre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`IDgenre`));


-- -----------------------------------------------------
-- Table `mydb`.`format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`format` ;

CREATE TABLE IF NOT EXISTS `mydb`.`format` (
  `IDformat` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IDformat`));


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `ID_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`ID_category`));


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`images` ;

CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `IDImages` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(350) NOT NULL,
  PRIMARY KEY (`IDImages`));


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `ID_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL NOT NULL,
  `stock` INT NULL,
  `stock_min` INT NULL,
  `stock_max` INT NULL,
  `description` TEXT(400) NULL,
  `artist` VARCHAR(100) NOT NULL,
  `visibility` INT NULL,
  `genres_IDgenre` INT NOT NULL,
  `format_IDformat` INT NOT NULL,
  `categories_ID_category` INT NOT NULL,
  `images_IDImages` INT NOT NULL,
  PRIMARY KEY (`ID_product`, `genres_IDgenre`, `format_IDformat`, `categories_ID_category`, `images_IDImages`),
  INDEX `fk_products_genres1_idx` (`genres_IDgenre` ASC) VISIBLE,
  INDEX `fk_products_format1_idx` (`format_IDformat` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`categories_ID_category` ASC) VISIBLE,
  INDEX `fk_products_images1_idx` (`images_IDImages` ASC) VISIBLE,
  CONSTRAINT `fk_products_genres1`
    FOREIGN KEY (`genres_IDgenre`)
    REFERENCES `mydb`.`genres` (`IDgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_format1`
    FOREIGN KEY (`format_IDformat`)
    REFERENCES `mydb`.`format` (`IDformat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_ID_category`)
    REFERENCES `mydb`.`categories` (`ID_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_images1`
    FOREIGN KEY (`images_IDImages`)
    REFERENCES `mydb`.`images` (`IDImages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`orderStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orderStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orderStatus` (
  `idorderStatus` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorderStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payments` (
  `idpayments` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idpayments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `orderStatus_id` INT NOT NULL,
  `payments_id` INT NOT NULL,
  `number` INT NOT NULL,
  `date` DATE NULL,
  `total` DECIMAL NULL,
  PRIMARY KEY (`idorders`, `users_id`, `orderStatus_id`, `payments_id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_orderStatus1_idx` (`orderStatus_id` ASC) VISIBLE,
  INDEX `fk_orders_payments1_idx` (`payments_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`roles_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_orderStatus1`
    FOREIGN KEY (`orderStatus_id`)
    REFERENCES `mydb`.`orderStatus` (`idorderStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_payments1`
    FOREIGN KEY (`payments_id`)
    REFERENCES `mydb`.`payments` (`idpayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orderDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orderDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT NOT NULL,
  `products_ID_product` INT NOT NULL,
  `quantity` DECIMAL NOT NULL,
  `subtotal` DECIMAL NULL,
  PRIMARY KEY (`id`, `orders_id`, `products_ID_product`),
  INDEX `fk_orderDetails_products1_idx` (`products_ID_product` ASC) VISIBLE,
  CONSTRAINT `fk_ordersDetails_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`orders` (`idorders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderDetails_products1`
    FOREIGN KEY (`products_ID_product`)
    REFERENCES `mydb`.`products` (`ID_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
